export let LANGDATA = {
  de: {
    infoTop:
      "Dieses Projekt wurde realisiert von Felix Neumann und Emil Hausmann.",
    settings: "Einstellungen",
    language: "Sprache",
    chemistryUtil: "Chemie Utility",
    cookieMessage:
      "Diese Webseite benutzt Cookies um das Nutzererlebnis zu optimieren.",
    elementList: "Liste der Elemente",
    atomicNumber: "Ordnungszahl",
    symbol: "Symbol",
    name: "Name",
    molarMass: "molare Masse (g/mol)",
    molarMassTitle: "Molare Masse",
    electronegativity: "Elektronegativität (Pauling)",
    nucleonNumber: "Nukleonenanzahl",
    density: "Dichte (g/cm3 bzw. g/l)",
    meltingPoint: "Schmelzpunkt (°C)",
    boilingPoint: "Siedepunkt (°C)",
    state: "Zustand (20°C)",
    gas: "gasförmig",
    liquid: "flüssig",
    solid: "fest",
    formulaBalancer: "Formelausgleicher",
    stoichiometry: "Stöchiometrie",
    formulaBalancerHint1:
      "Tiefgestellte Zahlen sind als normale Zahlen zu schreiben. (z.B. H2O)",
    formulaBalancerHint2: "Es sind nur Summenformeln zulässig.",
    formulaBalancerHint3:
      "Als Reaktionspfeil ist ein einfaches = zu verwenden.",
    formulaBalancerHint4: "Klammern sind nicht zulässig.",
    go: "Los",
    enterFormulaHere: "Formel hier eingeben",
    stoichiometryHint1:
      "Beide Stoff-Felder müssen mit Summenformeln ausgefüllt werden. Entweder ein Masse oder ein Stoffmenge Feld muss freigelassen werden.",
    stoichiometryHint2: "Klammern sind nicht zulässig.",
    substance1: "Stoff 1",
    substance2: "Stoff 2",
    mass1: "Masse 1",
    mass2: "Masse 2",
    amount1: "Stoffmenge 1",
    amount2: "Stoffmenge 2",
    molarMassHint1: "Ein Molekül als Summenformel eingeben.",
    molarMassHint2: "Klammern sind nicht zulässig.",
    enterMoleculeHere: "Molekül hier eingeben",
    theme: "Design",
    credits: "Namensnennung",
    dark: "Dunkel",
    light: "Hell",
    bisque: "Biskuit",
    black: "Schwarz",
    blue: "Blau",
    green: "Grün",
    red: "Rot",
    designConcept: "Design Konzept",
    font: "Schriftart",
    space: "Weltraum",
    particles: "Partikel",
    unitsTitle: "Einheitenumrechner",
    help: "Hilfe",
    websiteHelp: "Website Hilfe",
    delphiHelp: "Delphi Hilfe",
  },
  en: {
    infoTop: "This project was realized by Felix Neumann and Emil Hausmann.",
    settings: "Settings",
    language: "Language",
    chemistryUtil: "Chemistry Utility",
    cookieMessage: "This website uses cookies to optimize the user experience.",
    elementList: "List of elements",
    atomicNumber: "atomic number",
    symbol: "symbol",
    name: "name",
    molarMass: "molar mass (g/mol)",
    electronegativity: "electronegativity (Pauling)",
    nucleonNumber: "nucleon number",
    density: "density (g/cm3 resp. g/l)",
    meltingPoint: "melting point (°C)",
    boilingPoint: "boiling point (°C)",
    state: "state (20°C)",
    gas: "gas",
    liquid: "liquid",
    solid: "solid",
    formulaBalancer: "Formula balancer",
    stoichiometry: "Stoichiometry",
    molarMassTitle: "Molar mass",
    formulaBalancerHint1:
      "Subscript numbers are to be written as normal numbers. (e.g. H2O)",
    formulaBalancerHint2: "Only sum formulas are permitted.",
    formulaBalancerHint3: "A simple = is to be used as a reaction arrow.",
    formulaBalancerHint4: "Parentheses are not allowed.",
    go: "Go",
    enterFormulaHere: "Enter formula here",
    stoichiometryHint1:
      "Both substance fields must be filled in with sum formulas. Either a mass or a substance quantity field must be left blank.",
    stoichiometryHint2: "Parentheses are not allowed.",
    substance1: "Substance 1",
    substance2: "Substance 2",
    mass1: "Mass 1",
    mass2: "Mass 2",
    amount1: "Substance quantity 1",
    amount2: "Substance quantity 2",
    molarMassHint1: "Enter a molecule as a sum formula.",
    molarMassHint2: "Parentheses are not allowed.",
    enterMoleculeHere: "Enter molecule here",
    theme: "Theme",
    credits: "Credits",
    dark: "Dark",
    light: "Light",
    bisque: "Bisque",
    black: "Black",
    blue: "Blue",
    green: "Green",
    red: "Red",
    designConcept: "Design Concept",
    font: "Font",
    space: "Space",
    particles: "Particles",
    unitsTitle: "Unit converter",
    help: "Help",
    websiteHelp: "Website Help",
    delphiHelp: "Delphi Help",
  },
};
