export const UNITS = [
  {
    Name: "g",
    Kategorie: "Masse",
    Standard: true,
    Multiply: "",
    Add: "",
  },
  {
    Name: "kg",
    Kategorie: "Masse",
    Standard: false,
    Multiply: 0.001,
    Add: 0,
  },
  {
    Name: "t",
    Kategorie: "Masse",
    Standard: false,
    Multiply: 0.000001,
    Add: 0,
  },
  {
    Name: "mg",
    Kategorie: "Masse",
    Standard: false,
    Multiply: 1000,
    Add: 0,
  },
  {
    Name: "l",
    Kategorie: "Volumen",
    Standard: true,
    Multiply: null,
    Add: null,
  },
  {
    Name: "ml",
    Kategorie: "Volumen",
    Standard: false,
    Multiply: 1000,
    Add: 0,
  },
  {
    Name: "dm^3",
    Kategorie: "Volumen",
    Standard: false,
    Multiply: 1,
    Add: 0,
  },
  {
    Name: "m^3",
    Kategorie: "Volumen",
    Standard: false,
    Multiply: 0.001,
    Add: 0,
  },
  {
    Name: "cm^3",
    Kategorie: "Volumen",
    Standard: false,
    Multiply: 1000,
    Add: 0,
  },
  {
    Name: "g/(cm^3)",
    Kategorie: "Dichte",
    Standard: true,
    Multiply: null,
    Add: null,
  },
  {
    Name: "g/l",
    Kategorie: "Dichte",
    Standard: false,
    Multiply: 0.001,
    Add: 0,
  },
  {
    Name: "g/(m^3)",
    Kategorie: "Dichte",
    Standard: false,
    Multiply: 0.000001,
    Add: 0,
  },
  {
    Name: "g/mol",
    Kategorie: "Molare Masse",
    Standard: true,
    Multiply: null,
    Add: null,
  },
  {
    Name: "kg/mol",
    Kategorie: "Molare Masse",
    Standard: false,
    Multiply: 0.001,
    Add: 0,
  },
  {
    Name: "mg/mol",
    Kategorie: "Molare Masse",
    Standard: false,
    Multiply: 1000,
    Add: 0,
  },
  {
    Name: "°C",
    Kategorie: "Temperatur",
    Standard: true,
    Multiply: null,
    Add: null,
  },
  {
    Name: "°F",
    Kategorie: "Temperatur",
    Standard: false,
    Multiply: 1.8,
    Add: 32,
  },
  {
    Name: "K",
    Kategorie: "Temperatur",
    Standard: false,
    Multiply: 1,
    Add: 273.15,
  },
  {
    Name: "(cm^3)/mol",
    Kategorie: "Molares Volumen",
    Standard: true,
    Multiply: null,
    Add: null,
  },
  {
    Name: "l/mol",
    Kategorie: "Molares Volumen",
    Standard: false,
    Multiply: 0.001,
    Add: 0,
  },
  {
    Name: "(m^3)/mol",
    Kategorie: "Molares Volumen",
    Standard: false,
    Multiply: 0.000001,
    Add: 0,
  },
];
